package spring_web_xml_config_demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import spring_web_xml_config_demo.entity.UseT;
import spring_web_xml_config_demo.entity.UseTExample;

public interface UseTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    long countByExample(UseTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int deleteByExample(UseTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int insert(UseT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int insertSelective(UseT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    List<UseT> selectByExample(UseTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    UseT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") UseT record, @Param("example") UseTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int updateByExample(@Param("record") UseT record, @Param("example") UseTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int updateByPrimaryKeySelective(UseT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table use_t
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    int updateByPrimaryKey(UseT record);
}