package spring_web_xml_config_demo.entity;

public class UseT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_t.id
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column use_t.name
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_t.id
     *
     * @return the value of use_t.id
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_t.id
     *
     * @param id the value for use_t.id
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column use_t.name
     *
     * @return the value of use_t.name
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column use_t.name
     *
     * @param name the value for use_t.name
     *
     * @mbg.generated Thu Apr 19 16:49:10 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}